#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
#Browser Configuration
browser = chrome
#Credentials
username = Admin
password = admin123
#ImplicitWait (In Seconds)
implicitWait = 1
#ExplicitWait
explicitWait = 20

